const a = 1

try {
	const { res } = a

	console.log({ res })
} catch (err) {
	console.error(err)
}
